# Please modify the following contents
vn:
  inits:
    - vnCode: UDPN000111
      vnNodeName: UDPN000111 name
      vnRegion: China
      vnInformation: This is perfect VN-NODE-China.
      vnUrl: http://16.163.247.242:30081
    - vnCode: UDPN000111
      vnNodeName: UDPN000111 name
      vnRegion: China
      vnInformation: This is perfect VN-NODE-China.
      vnUrl: http://16.163.247.242:30081
