# Please modify the following contents
vn:
  inits:
    - vnCode: VN0000002
      vnNodeName: VN-RED1
      vnRegion: China
      vnInformation: This is perfect VN-NODE-China.
      vnUrl: https://pre-vngw.udpn.io:443
    - vnCode: VN0000002
      vnNodeName: VN-RED1
      vnRegion: China
      vnInformation: This is perfect VN-NODE-China.
      vnUrl: https://pre-vngw.udpn.io:443