# Please modify the following contents
vn:
  inits:
    - vnCode: VN0000001
      vnNodeName: VN0000001 name
      vnRegion: China
      vnInformation: This is perfect VN-NODE-China.
      vnUrl: https://vngateway.udpn.io:443
    - vnCode: VN0000001
      vnNodeName: VN0000001 name
      vnRegion: China
      vnInformation: This is perfect VN-NODE-China.
      vnUrl: https://vngateway.udpn.io:443