version: '3.6'
services:

  mysql:
    container_name: mysql
    image: mysql:5.7.31
    restart: always
    ports:
      - ${MYSQL_MASTER_PORT}:${MYSQL_MASTER_PORT}
    privileged: true
    volumes:
      - $MYSQL_DATA/data:/var/lib/mysql
      - $MYSQL_DATA/my.cnf:/etc/mysql/my.cnf
      - /etc/localtime:/etc/localtime
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PWD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PWD}
    networks:
      udpn-bn:
        ipv4_address: 172.16.139.100

  redis:
    image: redis:6.2.5
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:
      - $REDIS_DATA/data:/data:rw
      - $REDIS_DATA/redis.conf:/redis.conf:rw
      - /etc/localtime:/etc/localtime
    command:
      --requirepass "${REDIS_PASSWORD}"
    privileged: true
    networks:
      udpn-bn:
        ipv4_address: 172.16.139.101


  bneureka:
    image: openjdk:8u102-jre
    container_name: ${EUREKA_CONTAINER_NAME}
    restart: always
    volumes: 
        - ${BN_DATA_VOLUMES}:/data
        - /etc/localtime:/etc/localtime:ro
    environment:
        - TZ=Asia/Shanghai
        - server.port=${EUREKA_PORT}
        - logging.logpath=/data/logs
        - logging.level.root=info
        - spring.security.user.name=${EUREKA_USER}
        - spring.security.user.password=${EUREKA_PWD}
        - eureka.client.service-url.defaultZone=http://${EUREKA_CONTAINER_NAME}:${EUREKA_PORT}/eureka
    command: /bin/bash -c "java -Djava.security.egd=file:/dev/./urandom -jar /data/redeureka-0.0.1-SNAPSHOT.jar"
    ports:
        - ${EUREKA_PORT}:${EUREKA_PORT}
    networks:
      udpn-bn:
        ipv4_address: 172.16.139.102

  bninit:
    image: openjdk:8u102-jre
    container_name: ${BN_INIT_CONTAINER_NAME}
    restart: always
    volumes: 
        - ${BN_DATA_VOLUMES}:/data
        - /etc/localtime:/etc/localtime:ro
    environment:
        - TZ=Asia/Shanghai
        - server.port=${BN_INIT_PORT}
        - logging.logpath=${LOG_SAVE_DIR}
        - logging.level.root=info
        - mysql.master.url=jdbc:mysql://${MYSQL_MASTER_HOST}:${MYSQL_MASTER_PORT}/${MYSQL_DATABASE}?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        - mysql.master.username=${MYSQL_USER}
        - mysql.master.password=${MYSQL_PWD}
        - mysql.slave.url=jdbc:mysql://${MYSQL_SLAVE_HOST}:${MYSQL_SLAVE_PORT}/${MYSQL_DATABASE}?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        - mysql.slave.username=${MYSQL_USER}
        - mysql.slave.password=${MYSQL_PWD}
        - spring.redis.host=${REDIS_HOST}
        - spring.redis.port=${REDIS_PORT}
        - spring.redis.password=${REDIS_PASSWORD}
        - spring.redis.database=${REDIS_DATABASE}
        - vn.init.file.path=${VN_INIT_FILE}
        - eureka.client.service-url.defaultZone=http://${EUREKA_USER}:${EUREKA_PWD}@${EUREKA_CONTAINER_NAME}:${EUREKA_PORT}/eureka
        - spring.flyway.enabled=true
        - did.proxy.properties.file=${DID_PROXY_PROP_FILE}
        - did.proxyMode=${DID_PROXY_MODE}
        - did.proxy.url=${DID_PROXY_URL}
        - besu.nodeUrl=${BESU_NODE_URL}
        - besu.nodePrivateKey=${BESU_NODE_PRIVATEKEY}
        - besu.didContAddress=${BESU_DID_CONTADDRESS}
        - besu.cptContAddress=${BESU_CPT_CONTADDRESS}
        - besu.authIssuerAddress=${BESU_AUTHISSUERADDRESS}
        - is.online=${IS_ONLINE}
    command: /bin/bash -c "java -Djava.security.egd=file:/dev/./urandom -jar /data/bn-init-0.0.1-SNAPSHOT.jar"
    ports:
        - ${BN_INIT_PORT}:${BN_INIT_PORT}
    depends_on:
      - mysql
      - redis
      - bneureka
    networks:
      udpn-bn:
        ipv4_address: 172.16.139.103

  bngateway:
    image: openjdk:8u102-jre
    container_name: ${BN_GATEWAY_CONTAINER_NAME}
    restart: always
    volumes: 
        - ${BN_DATA_VOLUMES}:/data
        - ${BN_DATA_VOLUMES}/init:/data/init
        - /etc/localtime:/etc/localtime:ro
    environment:
        - TZ=Asia/Shanghai
        - server.port=${BN_GATEWAY_PORT}
        - logging.logpath=${LOG_SAVE_DIR}
        - logging.level.root=info
        - eureka.client.service-url.defaultZone=http://${EUREKA_USER}:${EUREKA_PWD}@${EUREKA_CONTAINER_NAME}:${EUREKA_PORT}/eureka
    command: /bin/bash -c "java -Djava.security.egd=file:/dev/./urandom -jar /data/bn-gateway-0.0.1-SNAPSHOT.jar"
    ports:
        - ${BN_GATEWAY_PORT}:${BN_GATEWAY_PORT}
    depends_on:
      - bninit
    networks:
      udpn-bn:
        ipv4_address: 172.16.139.104

  bnevent:
    image: openjdk:8u102-jre
    container_name: ${BN_EVENT_CONTAINER_NAME}
    restart: always
    volumes: 
        - ${BN_DATA_VOLUMES}:/data
        - /etc/localtime:/etc/localtime:ro
    environment:
        - TZ=Asia/Shanghai
        - server.port=${BN_EVENT_PORT}
        - logging.logpath=${LOG_SAVE_DIR}
        - logging.level.root=info
        - mysql.master.url=jdbc:mysql://${MYSQL_MASTER_HOST}:${MYSQL_MASTER_PORT}/${MYSQL_DATABASE}?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        - mysql.master.username=${MYSQL_USER}
        - mysql.master.password=${MYSQL_PWD}
        - mysql.slave.url=jdbc:mysql://${MYSQL_SLAVE_HOST}:${MYSQL_SLAVE_PORT}/${MYSQL_DATABASE}?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        - mysql.slave.username=${MYSQL_USER}
        - mysql.slave.password=${MYSQL_PWD}
        - eureka.client.service-url.defaultZone=http://${EUREKA_USER}:${EUREKA_PWD}@${EUREKA_CONTAINER_NAME}:${EUREKA_PORT}/eureka
    command: /bin/bash -c "java -Djava.security.egd=file:/dev/./urandom -jar /data/bn-event-0.0.1-SNAPSHOT.jar"
    ports:
        - ${BN_EVENT_PORT}:${BN_EVENT_PORT}
    depends_on:
      - bninit
    networks:
      udpn-bn:
        ipv4_address: 172.16.139.105

  bnpermission:
    image: openjdk:8u102-jre
    container_name: ${BN_PERMISSION_CONTAINER_NAME}
    restart: always
    volumes: 
        - ${BN_DATA_VOLUMES}:/data
        - /etc/localtime:/etc/localtime:ro
    environment:
        - TZ=Asia/Shanghai
        - server.port=${BN_PERMISSION_PORT}
        - logging.logpath=${LOG_SAVE_DIR}
        - logging.level.root=debug
        - mysql.master.url=jdbc:mysql://${MYSQL_MASTER_HOST}:${MYSQL_MASTER_PORT}/${MYSQL_DATABASE}?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        - mysql.master.username=${MYSQL_USER}
        - mysql.master.password=${MYSQL_PWD}
        - mysql.slave.url=jdbc:mysql://${MYSQL_SLAVE_HOST}:${MYSQL_SLAVE_PORT}/${MYSQL_DATABASE}?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        - mysql.slave.username=${MYSQL_USER}
        - mysql.slave.password=${MYSQL_PWD}
        - eureka.client.service-url.defaultZone=http://${EUREKA_USER}:${EUREKA_PWD}@${EUREKA_CONTAINER_NAME}:${EUREKA_PORT}/eureka
    command: /bin/bash -c "java -Djava.security.egd=file:/dev/./urandom -jar /data/bn-permission-0.0.1-SNAPSHOT.jar"
    ports:
        - ${BN_PERMISSION_PORT}:${BN_PERMISSION_PORT}
    depends_on:
      - bninit
    networks:
      udpn-bn:
        ipv4_address: 172.16.139.106

  bnprocess:
    image: openjdk:8u102-jre
    container_name: ${BN_PROCESS_CONTAINER_NAME}
    restart: always
    volumes: 
        - ${BN_DATA_VOLUMES}:/data
        - /etc/localtime:/etc/localtime:ro
    environment:
        - TZ=Asia/Shanghai
        - server.port=${BN_PROCESS_PORT}
        - logging.logpath=${LOG_SAVE_DIR}
        - logging.level.root=debug
        - mysql.master.url=jdbc:mysql://${MYSQL_MASTER_HOST}:${MYSQL_MASTER_PORT}/${MYSQL_DATABASE}?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        - mysql.master.username=${MYSQL_USER}
        - mysql.master.password=${MYSQL_PWD}
        - mysql.slave.url=jdbc:mysql://${MYSQL_SLAVE_HOST}:${MYSQL_SLAVE_PORT}/${MYSQL_DATABASE}?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        - mysql.slave.username=${MYSQL_USER}
        - mysql.slave.password=${MYSQL_PWD}
        - spring.redis.host=${REDIS_HOST}
        - spring.redis.port=${REDIS_PORT}
        - spring.redis.password=${REDIS_PASSWORD}
        - spring.redis.database=${REDIS_DATABASE}
        - did.proxy.properties.file=${DID_PROXY_PROP_FILE}
        - eureka.client.service-url.defaultZone=http://${EUREKA_USER}:${EUREKA_PWD}@${EUREKA_CONTAINER_NAME}:${EUREKA_PORT}/eureka
        - did.proxyMode=${DID_PROXY_MODE}
        - did.proxy.url=${DID_PROXY_URL}
        - besu.nodeUrl=${BESU_NODE_URL}
        - besu.nodePrivateKey=${BESU_NODE_PRIVATEKEY}
        - besu.didContAddress=${BESU_DID_CONTADDRESS}
        - besu.cptContAddress=${BESU_CPT_CONTADDRESS}
        - besu.authIssuerAddress=${BESU_AUTHISSUERADDRESS}
    command: /bin/bash -c "java -Djava.security.egd=file:/dev/./urandom -jar /data/bn-processcore-0.0.1-SNAPSHOT.jar"
    ports:
        - ${BN_PROCESS_PORT}:${BN_PROCESS_PORT}
    depends_on:
      - bninit
    networks:
      udpn-bn:
        ipv4_address: 172.16.139.107

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 81:81
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/dist/web:/usr/share/nginx/html/web
      - ./nginx/dist/bnweb:/usr/share/nginx/html/bnweb
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - bngateway
    networks:
      udpn-bn:
        ipv4_address: 172.16.139.108

networks:
  udpn-bn:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.139.0/24
