version: '3.6'
services:

  mysql:
    image: mysql:5.7.31
    container_name: mysql
    restart: always
    privileged: true
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PWD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PWD}
      # - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ${BN_DATA_VOLUMES}/mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime
    ports:
      - ${MYSQL_MASTER_PORT}:3306
    networks:
      - udpn-bn
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1s
      timeout: 3s
      retries: 30

  redis:
    image: redis:6.2.5
    container_name: redis
    restart: always
    privileged: true
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    command:
      --requirepass "${REDIS_PASSWORD}"
    volumes:
      - ${BN_DATA_VOLUMES}/redis/data:/data:rw
      - ./redis/redis.conf:/redis.conf:rw
      - /etc/localtime:/etc/localtime
    privileged: true
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - udpn-bn
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  bneureka: 
    image: udpnnetwork/redeureka:releaseV1.1.3
    container_name: bneureka
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - server.port=8761
      - logging.logpath=/data/logs
      - logging.level.root=info
      - spring.security.user.name=${EUREKA_USER}
      - spring.security.user.password=${EUREKA_PWD}
      - eureka.client.service-url.defaultZone=http://bneureka:${EUREKA_PORT}/eureka
      - feign.client.config.default.connect-timeout=30000
      - feign.client.config.default.read-timeout=30000
    command: ["/bin/bash", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
    volumes:
      - ${BN_DATA_VOLUMES}/log:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
        - ${EUREKA_PORT}:8761
    depends_on:
      - mysql
      - redis
    networks:
        - udpn-bn
    healthcheck: 
      test: ["CMD-SHELL", "curl -sS 'http://localhost:8761' || exit 1"]
      interval: 5s 
      timeout: 5s 
      retries: 3 
      start_period: 600s 

  bninit:
    image: udpnnetwork/bn-init:v1.4.4.0.0
    container_name: bninit
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - server.port=8080
      - logging.logpath=${LOG_SAVE_DIR}
      - logging.level.root=info
      - mysql.master.url=jdbc:mysql://${MYSQL_MASTER_HOST}:${MYSQL_MASTER_PORT}/${MYSQL_DATABASE}?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      - mysql.master.username=${MYSQL_USER}
      - mysql.master.password=${MYSQL_PWD}
      - mysql.slave.url=jdbc:mysql://${MYSQL_SLAVE_HOST}:${MYSQL_SLAVE_PORT}/${MYSQL_DATABASE}?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai       
      - mysql.slave.username=${MYSQL_USER}
      - mysql.slave.password=${MYSQL_PWD}
      - spring.redis.host=${REDIS_HOST}
      - spring.redis.port=${REDIS_PORT}
      - spring.redis.password=${REDIS_PASSWORD}
      - spring.redis.database=${REDIS_DATABASE}
      - vn.init.file.path=/data/init/vninit.yml
      - eureka.client.service-url.defaultZone=http://${EUREKA_USER}:${EUREKA_PWD}@bneureka:${EUREKA_PORT}/eureka
      - spring.flyway.enabled=true
      - did.proxy.properties.file=${DID_PROXY_PROP_FILE}
      - did.proxyMode=${DID_PROXY_MODE}
      - did.proxy.url=${DID_PROXY_URL}
      - besu.nodeUrl=${BESU_NODE_URL}
      - besu.nodePrivateKey=${BESU_NODE_PRIVATEKEY}
      - besu.didContAddress=${BESU_DID_CONTADDRESS}
      - besu.cptContAddress=${BESU_CPT_CONTADDRESS}
      - besu.authIssuerAddress=${BESU_AUTHISSUERADDRESS}
      - is.online=${IS_ONLINE}
      - did.private.key=${DID_PRIVATE_KEY}
      - ENV_VN_GATEWAY=${VN_GATEWAY}
      - ENV_VN_CODE=${VN_CODE}
      - ENV_BESU_DID_CONTADDRESS=${BESU_DID_CONTADDRESS}
      - ENV_BESU_CPT_CONTADDRESS=${BESU_CPT_CONTADDRESS}
      - ENV_BESU_AUTHISSUERADDRESS=${BESU_AUTHISSUERADDRESS}
      - feign.client.config.default.connect-timeout=30000
      - feign.client.config.default.read-timeout=30000
    #command: 
    #  - /bin/bash
    #  - -c
    #  - "envsubst '$${ENV_VN_GATEWAY},$${ENV_VN_CODE}' </data/init/vninit.template> /data/init/vninit.yml && 
    #     envsubst '$${ENV_VN_GATEWAY},$${ENV_BESU_DID_CONTADDRESS},$${ENV_BESU_CPT_CONTADDRESS},$${ENV_BESU_AUTHISSUERADDRESS}' </data/init/did_proxy.template> /data/init/did_proxy.properties && \
    #     exec java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"
    command: ["/bin/bash", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
    volumes:
      - ${BN_DATA_VOLUMES}/log:/data:rw
      - ./bnserver/init/vninit.yml:/data/init/vninit.yml:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${BN_INIT_PORT}:8080
    depends_on:
      - bneureka
    networks:
      - udpn-bn
    healthcheck: 
      test: ["CMD-SHELL", "curl -sS 'http://localhost:8080' || exit 1"]
      interval: 5s 
      timeout: 5s 
      retries: 3 
      start_period: 600s 

  bngateway:
    image: udpnnetwork/bn-gateway:releaseV1.1.3
    container_name: bngateway
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - server.port=8080
      - logging.logpath=${LOG_SAVE_DIR}
      - logging.level.root=info
      - eureka.client.service-url.defaultZone=http://${EUREKA_USER}:${EUREKA_PWD}@bneureka:${EUREKA_PORT}/eureka
      - feign.client.config.default.connect-timeout=30000
      - feign.client.config.default.read-timeout=30000
    command: ["/bin/bash", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
    volumes:
      - ${BN_DATA_VOLUMES}/log:/data
      - ./bnserver/init:/data/init
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${BN_GATEWAY_PORT}:8080
    depends_on:
      - bneureka
      - bninit
    networks:
      - udpn-bn
    healthcheck: 
      test: ["CMD-SHELL", "curl -sS 'http://localhost:8080' || exit 1"]
      interval: 5s 
      timeout: 5s 
      retries: 3 
      start_period: 600s 


  bn1-event:
    image: udpnnetwork/bn-event:v1.4.4.0.0
    container_name: bn1-event
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - server.port=8080
      - logging.logpath=${LOG_SAVE_DIR}
      - logging.level.root=info
      - mysql.master.url=jdbc:mysql://${MYSQL_MASTER_HOST}:${MYSQL_MASTER_PORT}/${MYSQL_DATABASE}?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      - mysql.master.username=${MYSQL_USER}
      - mysql.master.password=${MYSQL_PWD}
      - mysql.slave.url=jdbc:mysql://${MYSQL_SLAVE_HOST}:${MYSQL_SLAVE_PORT}/${MYSQL_DATABASE}?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      - mysql.slave.username=${MYSQL_USER}
      - mysql.slave.password=${MYSQL_PWD}
      - eureka.client.service-url.defaultZone=http://${EUREKA_USER}:${EUREKA_PWD}@bneureka:${EUREKA_PORT}/eureka
      #- event.server.start=${EVENT_SERVER_START}
      - receipt.task.cron=${RECEIPT_TASK_CRON}
      - eventTask.enabled=${EVENTTASK_ENABLED}
      - task.event.filter.manage=${TASK_EVENT_FILTER_MANAGE}
      - spring.redis.host=${REDIS_HOST}
      - spring.redis.port=${REDIS_PORT}
      - spring.redis.password=${REDIS_PASSWORD}
      - spring.redis.database=${REDIS_DATABASE}
      - did.private.key=${DID_PRIVATE_KEY}
      - feign.client.config.default.connect-timeout=30000
      - feign.client.config.default.read-timeout=30000

    command: ["/bin/bash", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
    volumes:
      - ${BN_DATA_VOLUMES}/log:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${BN_EVENT_PORT}:8080
    depends_on:
      - bngateway
    networks:
      - udpn-bn

  bnpermission:
    image: udpnnetwork/bn-permission:releaseV1.1.3
    container_name: bnpermission
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - server.port=8080
      - logging.logpath=${LOG_SAVE_DIR}
      - logging.level.root=info
      - mysql.master.url=jdbc:mysql://${MYSQL_MASTER_HOST}:${MYSQL_MASTER_PORT}/${MYSQL_DATABASE}?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      - mysql.master.username=${MYSQL_USER}
      - mysql.master.password=${MYSQL_PWD}
      - mysql.slave.url=jdbc:mysql://${MYSQL_SLAVE_HOST}:${MYSQL_SLAVE_PORT}/${MYSQL_DATABASE}?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      - mysql.slave.username=${MYSQL_USER}
      - mysql.slave.password=${MYSQL_PWD}
      - eureka.client.service-url.defaultZone=http://${EUREKA_USER}:${EUREKA_PWD}@bneureka:${EUREKA_PORT}/eureka
      - feign.client.config.default.connect-timeout=30000
      - feign.client.config.default.read-timeout=30000
    command: ["/bin/bash", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
    volumes:
      - ${BN_DATA_VOLUMES}/log:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${BN_PERMISSION_PORT}:8080
    depends_on:
      - bngateway
    networks:
      - udpn-bn
    healthcheck: 
      test: ["CMD-SHELL", "curl -sS 'http://localhost:8080' || exit 1"]
      interval: 5s 
      timeout: 5s 
      retries: 3 
      start_period: 600s 

  bnprocess:
    image: udpnnetwork/bn-processcore:v1.4.4.0.0
    container_name: bnprocess
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - server.port=8080
      - logging.logpath=${LOG_SAVE_DIR}
      - logging.level.root=info
      - mysql.master.url=jdbc:mysql://${MYSQL_MASTER_HOST}:${MYSQL_MASTER_PORT}/${MYSQL_DATABASE}?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      - mysql.master.username=${MYSQL_USER}
      - mysql.master.password=${MYSQL_PWD}
      - mysql.slave.url=jdbc:mysql://${MYSQL_SLAVE_HOST}:${MYSQL_SLAVE_PORT}/${MYSQL_DATABASE}?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      - mysql.slave.username=${MYSQL_USER}
      - mysql.slave.password=${MYSQL_PWD}
      - spring.redis.host=${REDIS_HOST}
      - spring.redis.port=${REDIS_PORT}
      - spring.redis.password=${REDIS_PASSWORD}
      - spring.redis.database=${REDIS_DATABASE}
      - did.proxy.properties.file=${DID_PROXY_PROP_FILE}
      - eureka.client.service-url.defaultZone=http://${EUREKA_USER}:${EUREKA_PWD}@bneureka:${EUREKA_PORT}/eureka
      - did.proxyMode=${DID_PROXY_MODE}
      - did.proxy.url=${DID_PROXY_URL}
      - besu.nodeUrl=${BESU_NODE_URL}
      - besu.nodePrivateKey=${BESU_NODE_PRIVATEKEY}
      - besu.didContAddress=${BESU_DID_CONTADDRESS}
      - besu.cptContAddress=${BESU_CPT_CONTADDRESS}
      - besu.authIssuerAddress=${BESU_AUTHISSUERADDRESS}
      - did.private.key=${DID_PRIVATE_KEY}
      - sol.file.path=${SOL_FILE_PATH}
      - task.Synchronous.audit.status=${TASK_SYNCHRONOUS_AUDIT_STATUS}
      #- auditstatustask.enabled=${AUDITSTATUSTASK_ENABLE}
      - spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE}
      - spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE}
      - task.refresh.application.state=${TASK_REFRESH_APPLICATION_STATE}"
      - solution.center.url=${SOLUTION_CENTER_URL}
      - feign.client.config.default.connect-timeout=30000
      - feign.client.config.default.read-timeout=30000
      - task.synchronous.authorize.bn.info=0 0/30 * * * ?
      - task.synchronous.callable.contract=0 0/3 * * * ?
      - task.rechain.contract.info=0 0/3 * * * ?
      - task.history.contract.info=0 0/3 * * * ?
      - processTask.enabled=true
    command: ["/bin/bash", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
    volumes:
      - ${BN_DATA_VOLUMES}/log:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${BN_PROCESS_PORT}:8080
    depends_on:
      - bngateway
    networks:
      - udpn-bn
    healthcheck: 
      test: ["CMD-SHELL", "curl -sS 'http://localhost:8080' || exit 1"]
      interval: 5s 
      timeout: 5s 
      retries: 3 
      start_period: 600s 

  bn-web:
    image: udpnnetwork/bn-web:v1.3.4.0.0
    container_name: bn-web
    restart: always
    volumes:
      - ${BN_DATA_VOLUMES}/bnweb/logs:/var/log/nginx
      - ./bnweb/config:/etc/nginx/conf.d/
    ports:
      - 8080:80
    depends_on:
      - bnpermission
      - bnprocess
    networks:
      - udpn-bn

  web_sandbox:
    image: udpnnetwork/web_sandbox:v1.4.4.0.0
    # build:
    #   context: ./web_sandbox/
    #   dockerfile: Dockerfile-sandbox
    container_name: web_sandbox
    restart: always
    environment:
      - ENV_VN_GATEWAY=${VN_GATEWAY}
    #command: /bin/sh -c "envsubst '$${ENV_VN_GATEWAY}' </etc/nginx/conf.d/default.template> /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;' "
    command: ["/bin/sh", "-c", "exec nginx -g 'daemon off;'"]
    volumes:
      - ${BN_DATA_VOLUMES}/web_sandbox/logs:/var/log/nginx
      - ./web_sandbox/config:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - bnpermission
      - bnprocess
    networks:
      - udpn-bn

networks:
  udpn-bn:
    driver: bridge
    name: udpn-bn