version: '3.6'
services:

  mysql:
    image: mysql:5.7.33
    container_name: mysql
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      #- MYSQL_USER=${MYSQL_USER}
      #- MYSQL_PASSWORD=${MYSQL_PWD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PWD}
      # - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ${BN_DATA_VOLUMES}/mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime
    ports:
      - ${MYSQL_MASTER_PORT}:3306
    networks:
      - udpn-bn
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1s
      timeout: 3s
      retries: 30

  redis:
    image: redis:6.2.5
    container_name: redis
    restart: always
    privileged: true
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    command:
      --requirepass "${REDIS_PASSWORD}"
    volumes:
      - ${BN_DATA_VOLUMES}/redis/data:/data:rw
      - ./redis/redis.conf:/redis.conf:rw
      - /etc/localtime:/etc/localtime
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - udpn-bn
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
  
  nacos:
    image: nacos/nacos-server:v2.2.3
    container_name: nacos
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      #- DB_SERVER=mysql
      #- DB_PORT=3306
      #- MYSQL_USER=root
      #- MYSQL_PASS=123456
      #- DB_NAME=nacos_config
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_SYSTEM_TYPE=nacos
      - NACOS_AUTH_IDENTITY_KEY=MREsiDDoiUVS6RkTFFLZ
      - NACOS_AUTH_IDENTITY_VALUE=XPcj38vDfjLLSH2g4DaVUokFMeP86WdEt83FYyC9
      - NACOS_AUTH_TOKEN=7KvQB2FgGU2PYpSDCE3sMj5THSfJLjFA32jdHb8NS74Nou2pGmt9wU4TNbggDiiEcFZv7d     
    volumes:
       - ${BN_DATA_VOLUMES}/nacos/logs/:/home/nacos/logs
       #- ./nacos/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - ${NACOS_WEB_PORT}:8848
      - ${NACOS_MANAGE_PORT}:9848
      - ${NACOS_GRPC_PORT}:7848
      - ${NACOS_PUB_PORT}:9849
    networks:
      - udpn-bn
    #healthcheck:
    #  test: ["CMD-SHELL", "curl -f 'http://localhost:8848/nacos/health'|| exit 1"]
    #  interval: 10s
    #  timeout: 5s
    #  retries: 3
    depends_on:
      mysql:
        condition: service_healthy

networks:
  udpn-bn:
    driver: bridge
    name: udpn-bn